server:
  port: 8081

spring:
  application:
    name: oauthclient
logging:
  level:
    org.springframework: WARN
    com.tcshop: DEBUG
#debug: true

oauth:
  loginUrl: http://localhost:8080/authorize
  redirectUrl: http://localhost:8081/oauthResult
  clientId: c1ebe466-1cdc-4bd3-ab69-77c3561b9dee
  clientSecret: d8346ea2-6017-43ed-ad68-19c0f971738b
  accessTokenUrl: http://localhost:8080/accessToken
  userInfoUrl: http://localhost:8080/userInfo